name: Bump version
on:   
  workflow_run:
    workflows: ["Compile Test"]
    branches: [master]
    types:
      - completed
      
jobs:
  build:
    if: github.repository_owner == 'BigWaspBackup' && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Generate changelog
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3.18.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        tag-prefix: 'v'
        output-file: 'CHANGELOG.md'
        skip-version-file: 'true'
        skip-on-empty: 'true'
        skip-commit: 'false'
        fallback-version: '7.20.12'
          
    - name: Create release
      uses: actions/create-release@v1.1.4
      if: ${{ steps.changelog.outputs.skipped == 'false' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
    
